const fieldMapping = {
    'Charaktername_page1': { jsonPath: 'name', type: 'string' },
    'Charaktername_page2': { jsonPath: 'name', type: 'string' },
    // Money Money Money
    'PM': { jsonPath: 'system.currency.pp', type: 'string' },
    'GM': { jsonPath: 'system.currency.gp', type: 'string' },
    'EM': { jsonPath: 'system.currency.ep', type: 'string' },
    'SM': { jsonPath: 'system.currency.sp', type: 'string' },
    'KM': { jsonPath: 'system.currency.cp', type: 'string' },
    //Char Stats
    'Str': { jsonPath: 'system.abilities.str.value', type: 'string' },
    'StrProf': { jsonPath: 'system.abilities.str.proficient', type: 'checkbox' },
    'Ges': { jsonPath: 'system.abilities.dex.value', type: 'string' },
    'GesProf': { jsonPath: 'system.abilities.dex.proficient', type: 'checkbox' },
    'Kon': { jsonPath: 'system.abilities.con.value', type: 'string' },
    'KonProf': { jsonPath: 'system.abilities.con.proficient', type: 'checkbox' },
    'Int': { jsonPath: 'system.abilities.int.value', type: 'string' },
    'IntProf': { jsonPath: 'system.abilities.int.proficient', type: 'checkbox' },
    'Wei': { jsonPath: 'system.abilities.wis.value', type: 'string' },
    'WeiProf': { jsonPath: 'system.abilities.wis.proficient', type: 'checkbox' },
    'Cha': { jsonPath: 'system.abilities.cha.value', type: 'string' },
    'ChaProf': { jsonPath: 'system.abilities.cha.proficient', type: 'checkbox' },
    //Skills
    'AkrobatikProf': { jsonPath: 'system.skills.acr.value', type: 'checkboxSkillProf' },
    'AkrobatikExp': { jsonPath: 'system.skills.acr.value', type: 'checkboxSkillExp' },
    'ArkaneKundeProf': { jsonPath: 'system.skills.arc.value', type: 'checkboxSkillProf' },
    'ArkaneKundeExp': { jsonPath: 'system.skills.arc.value', type: 'checkboxSkillExp' }, 
    'AthletikProf': { jsonPath: 'system.skills.ath.value', type: 'checkboxSkillProf' },
    'AthletikExp': { jsonPath: 'system.skills.ath.value', type: 'checkboxSkillExp' },
    'AuftretenProf': { jsonPath: 'system.skills.prf.value', type: 'checkboxSkillProf' },
    'AuftretenExp': { jsonPath: 'system.skills.prf.value', type: 'checkboxSkillExp' },
    'EinschüchternProf': { jsonPath: 'system.skills.itm.value', type: 'checkboxSkillProf' },
    'EinschüchternExp': { jsonPath: 'system.skills.itm.value', type: 'checkboxSkillExp' },
    'FingerfertigkeitProf': { jsonPath: 'system.skills.slt.value', type: 'checkboxSkillProf' },
    'FingerfertigkeitExp': { jsonPath: 'system.skills.slt.value', type: 'checkboxSkillExp' },
    'GeschichteProf': { jsonPath: 'system.skills.his.value', type: 'checkboxSkillProf' },
    'GeschichteExp': { jsonPath: 'system.skills.his.value', type: 'checkboxSkillExp' },
    'HeilkundeProf': { jsonPath: 'system.skills.med.value', type: 'checkboxSkillProf' },
    'HeilkundeExp': { jsonPath: 'system.skills.med.value', type: 'checkboxSkillExp' },
    'HeimlichkeitProf': { jsonPath: 'system.skills.ste.value', type: 'checkboxSkillProf' },
    'HeimlichkeitExp': { jsonPath: 'system.skills.ste.value', type: 'checkboxSkillExp' },
    'MitTierenUmgehenProf': { jsonPath: 'system.skills.ani.value', type: 'checkboxSkillProf' },
    'MitTierenUmgehenExp': { jsonPath: 'system.skills.ani.value', type: 'checkboxSkillExp' },
    'MotivErkennenProf': { jsonPath: 'system.skills.ins.value', type: 'checkboxSkillProf' },
    'MotivErkennenExp': { jsonPath: 'system.skills.ins.value', type: 'checkboxSkillExp' },
    'NachforschungenProf': { jsonPath: 'system.skills.inv.value', type: 'checkboxSkillProf' },
    'NachforschungenExp': { jsonPath: 'system.skills.inv.value', type: 'checkboxSkillExp' },
    'NaturkundeProf': { jsonPath: 'system.skills.nat.value', type: 'checkboxSkillProf' },
    'NaturkundeExp': { jsonPath: 'system.skills.nat.value', type: 'checkboxSkillExp' },
    'ReligionProf': { jsonPath: 'system.skills.rel.value', type: 'checkboxSkillProf' },
    'ReligionExp': { jsonPath: 'system.skills.rel.value', type: 'checkboxSkillExp' },
    'TäuschenProf': { jsonPath: 'system.skills.dec.value', type: 'checkboxSkillProf' },
    'TäuschenExp': { jsonPath: 'system.skills.dec.value', type: 'checkboxSkillExp' },
    'ÜberlebenskunstProf': { jsonPath: 'system.skills.sur.value', type: 'checkboxSkillProf' },
    'ÜberlebenskunstExp': { jsonPath: 'system.skills.sur.value', type: 'checkboxSkillExp' },
    'ÜberzeugenProf': { jsonPath: 'system.skills.per.value', type: 'checkboxSkillProf' },
    'ÜberzeugenExp': { jsonPath: 'system.skills.per.value', type: 'checkboxSkillExp' },
    'WahrnehmungProf': { jsonPath: 'system.skills.prc.value', type: 'checkboxSkillProf' },
    'WahrnehmungExp': { jsonPath: 'system.skills.prc.value', type: 'checkboxSkillExp' },
    //Hitpoints
    'TrefferpunkteMaximum': { jsonPath: 'system.attributes.hp.value', type: 'string' },
    'AktTrefferpunkte': { jsonPath: 'system.attributes.hp.value', type: 'string' },
    'TempTrefferpunkte': { jsonPath: 'system.attributes.hp.temp', type: 'string' },
    //Char Background and some Details from that
    'Volk': { jsonPath: 'system.details.race', type: 'searchID', attr: 'name' },
    'Bewegungsrate': { jsonPath: 'system.details.race', type: 'searchID', attr: 'system.movement.walk' },
    'Hintergrund': { jsonPath: 'system.details.background', type: 'searchID', attr: 'name' },
    'Erfahrungspunkte': { jsonPath: 'system.details.xp.value', type: 'string'},
    'KlasseUndStufe': { type: 'calculateValue', calcFunction: 'charClasses'},
    'Übungsbonus': { type: 'calculateValue', calcFunction: 'baseProficiency'},
    'GesamtTW': { type: 'calculateValue', calcFunction: 'hitDice'},
    //Armor Class, this is difficult becaus it has a lot of different calculations...
    'Rüstungsklasse': { type: 'calculateValue', calcFunction: 'armorClass'},
    'Sprache': { jsonPath: 'system.traits.languages.value', type: 'list', maxListItems: 6} ,
    'ÜbungWaffen': { jsonPath: 'system.traits.weaponProf.value', type: 'listProfWeapons', maxListItems: 6 },
    'ÜbungRüstung': { jsonPath: 'system.traits.armorProf.value', type: 'listProfArmor', maxListItems: 6 },
};
module.exports = { fieldMapping };